Repository wafflestudio/internhasha-web, pull requests merged in 2025-03, with the labels that each got.

#357 ✨ 아이디/비번 찾기 페이지 생성
  src/App.tsx
  src/components/ui/tabs.tsx
  src/entities/route.ts
  src/feature/auth/index.ts
  src/feature/auth/ui/findAccount/FindIdForm.tsx
  src/feature/auth/ui/findAccount/FindPasswordForm.tsx
  src/pages/FindAccountPage.tsx
  src/pages/SignInSelectPage.tsx
  src/shared/route/useRouteNavigation.ts
Labels: feature

#361 ✨ 아이디/비번 찾기 기능 API 연결
  src/api/apis/localServer/apis.ts
  src/feature/auth/service/authService.ts
  src/feature/auth/ui/findAccount/FindIdForm.tsx
  src/feature/auth/ui/findAccount/FindPasswordForm.tsx
Labels: feature

#365 💄 프로필 생성 페이지 UI 생성
  src/App.tsx
  src/components/field/ExternalLinkField.tsx
  src/components/field/HashtagField.tsx
  src/components/field/StringField.tsx
  src/components/field/StringFieldWithLabel.tsx
  src/components/field/TextareaField.tsx
  src/entities/route.ts
  src/feature/applicant/index.ts
  src/feature/applicant/presentation/applicantFormPresentation.ts
  src/feature/applicant/presentation/applicantInputPresentation.ts
  src/feature/applicant/ui/CreateProfileForm.tsx
  src/feature/company/ui/CreateCompanyForm.tsx
  src/lib/responseConverter.ts
  src/pages/CreateProfilePage.tsx
  src/shared/auth/ApplicantProtectedRoute.tsx
  src/shared/file/fileFormatPresentation.ts
  src/shared/route/useRouteNavigation.ts
Labels: feature

#363 💄 유저 커피챗 상세 페이지 ui 세팅
  src/components/modal/CancelCoffeeChatDeleteModal.tsx
  src/feature/coffeeChat/ui/CoffeeChatDetailView.tsx
Labels: feature

#367 👽️ 유저 관련 API 수정사항 반영 (회원가입, 로그인)
  src/App.tsx
  src/api/apis/localServer/apis.ts
  src/api/apis/localServer/schemas.ts
  src/api/index.ts
  src/components/modal/SignUpModal.tsx
  src/components/nav/GlobarNavigationBar.tsx
  src/entities/route.ts
  src/entities/user.ts
  src/feature/auth/index.ts
  src/feature/auth/service/authService.ts
  src/feature/auth/ui/findAccount/FindIdForm.tsx
  src/feature/auth/ui/findAccount/FindPasswordForm.tsx
  src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
  src/feature/auth/ui/signIn/LocalLoginForm.tsx
  src/feature/auth/ui/signUp/AddSignUpModal.tsx
  src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  src/feature/auth/ui/signUp/GoogleSocialSignUpButton.tsx
  src/feature/auth/ui/signUp/LocalSignUpForm.tsx
  src/feature/auth/ui/signUp/RedirectSignInModal.tsx
  src/feature/landing/ui/FilterSection.tsx
  src/feature/landing/ui/PostCard.tsx
  src/feature/post/ui/PostDetailView.tsx
  src/pages/FindAccountPage.tsx
  src/pages/LocalSignUpPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/shared/auth/AuthAdminSwitchRoute.tsx
  src/shared/auth/AuthProtectedRoute.tsx
  src/shared/auth/CompanyProtectedRoute.tsx
  src/shared/auth/ReissueRoute.tsx
  src/shared/context/RoleContext.ts
  src/shared/context/TokenContext.ts
  src/shared/role/state.ts
  src/shared/route/useRouteNavigation.ts
Labels: refactor

#373 🚑 role context가 잘못 지정된 부분 수정
  src/shared/auth/ApplicantProtectedRoute.tsx
Labels: bug

#376 ♻️ auth presentation 계층을 input과 form으로 분리하여 관리
  src/entities/input.ts
  src/feature/applicant/presentation/applicantFormPresentation.ts
  src/feature/auth/presentation/authFormPresentation.ts
  src/feature/auth/presentation/authInputPresentation.ts
  src/feature/auth/presentation/authPresentation.ts
  src/feature/auth/ui/findAccount/FindPasswordForm.tsx
  src/feature/auth/ui/signIn/LocalLoginForm.tsx
  src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  src/feature/auth/ui/signUp/LocalSignUpForm.tsx
Labels: refactor

#379 ✨ 회사/지원자 로그인 분리
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/tabs.tsx
  src/feature/auth/index.ts
  src/feature/auth/ui/signIn/ApplicantLocalLoginForm.tsx
  src/feature/auth/ui/signIn/CompanyLocalLoginForm.tsx
  src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  src/pages/SignInPage.tsx
  tailwind.config.js
Labels: feature

#381 ✨ 비밀번호 재발급 시 일반 메일 입력
  src/App.tsx
  src/entities/route.ts
  src/feature/auth/presentation/authInputPresentation.ts
  src/feature/auth/ui/findAccount/FindPasswordForm.tsx
  src/pages/ResetPasswordPage.tsx
  src/shared/route/useRouteNavigation.ts
Labels: feature

#382 ♻️ 상대경로 import를 허용하지 않는 eslint 룰 추가
  eslint.config.js
  src/App.tsx
  src/api/apis/externalServer/apis.ts
  src/api/apis/externalServer/index.ts
  src/api/apis/index.ts
  src/api/apis/localServer/apis.ts
  src/api/apis/localServer/index.ts
  src/api/client.ts
  src/api/index.ts
Labels: refactor

#390 ✨ 지원자 프로필 조회 페이지 생성
  src/App.tsx
  src/api/apis/localServer/apis.ts
  src/api/apis/localServer/schemas.ts
  src/components/button/LinkButton.tsx
  src/components/thumbnail/ThumbnailWithPresignedUrl.tsx
  src/components/ui/button.tsx
  src/feature/applicant/index.ts
  src/feature/applicant/service/applicantService.ts
  src/feature/applicant/ui/ApplicantInfo.tsx
  src/feature/applicant/ui/SkeletonApplicantInfo.tsx
  src/feature/coffeeChat/index.tsx
  src/feature/coffeeChat/ui/CoffeeChatNumberBadge.tsx
  src/feature/coffeeChat/ui/CoffeeChatTabs.tsx
  src/feature/post/ui/PostDetailView.tsx
  src/feature/user/index.ts
  src/feature/user/ui/MyInfo.tsx
  src/mocks/applicant/data.ts
  src/mocks/applicant/handlers.ts
  src/mocks/applicant/resolvers.ts
  src/mocks/applicant/schemas.ts
  src/mocks/auth/handlers.ts
  src/mocks/auth/resolvers.ts
  src/mocks/auth/schemas.ts
  src/mocks/handlers.ts
  src/pages/MyPage.tsx
  src/shared/context/ServiceContext.ts
Labels: feature

#398 ♻️ 커피챗목록 페이지 폰트 디자인 시스템 적용
  src/components/ui/badge.tsx
  src/components/ui/tagCoffeeChat.tsx
  src/feature/coffeeChat/ui/CoffeeChatListView.tsx
  src/feature/coffeeChat/ui/CoffeeChatNumberBadge.tsx
  src/feature/coffeeChat/ui/CompanyCoffeeChatListView.tsx
  src/feature/ventureCapital/ui/VentureCapitalMyTab.tsx
Labels: refactor

#392 🐛 query parameter 인코딩 적용
  src/api/apis/localServer/apis.ts
  src/api/apis/localServer/schemas.ts
  src/api/apis/utils/queryEncodeUtil.ts
  src/entities/post.ts
  src/feature/landing/ui/FilterSection.tsx
  src/feature/landing/ui/LandingPostView.tsx
  src/feature/post/service/postService.ts
  src/feature/ventureCapital/service/ventureCapitalService.ts
  src/feature/ventureCapital/ui/MyPostList.tsx
  src/pages/LandingPage.tsx
Labels: bug

#403 ✨ 마이페이지 네비게이션 시 tab 설정 가능하도록 수정
  src/App.tsx
  src/components/modal/RewritePostModal.tsx
  src/components/nav/GlobarNavigationBar.tsx
  src/entities/route.ts
  src/feature/applicant/presentation/applicantFormPresentation.ts
  src/feature/applicant/presentation/applicantInputPresentation.ts
  src/feature/applicant/ui/form/CreateProfileForm.tsx
  src/feature/applicant/ui/mypage/ApplicantInfo.tsx
  src/feature/auth/ui/signIn/ApplicantLocalLoginForm.tsx
  src/feature/auth/ui/signIn/CompanyLocalLoginForm.tsx
  src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  src/feature/auth/ui/signUp/LocalSignUpForm.tsx
  src/feature/coffeeChat/ui/detail/ApplicantCoffeeChatDetailView.tsx
  src/feature/coffeeChat/ui/mypage/common/NoCoffeeChat.tsx
  src/feature/company/presentation/companyFormPresentation.ts
  src/feature/company/presentation/companyInputPresentation.ts
  src/feature/company/ui/form/CreateCompanyForm.tsx
  src/feature/post/ui/detail/PostDetailView.tsx
  src/feature/post/ui/form/CreatePostForm.tsx
  src/feature/post/ui/landing/LandingPageView.tsx
  src/pages/ApplicantCoffeeChatDetailPage.tsx
  src/pages/ApplicantMyPage.tsx
  src/pages/CoffeeChatDetailPage.tsx
  src/pages/CompanyCoffeeChatDetailPage.tsx
  src/pages/CompanyMyPage.tsx
  src/pages/CreateCoffeeChatPage.tsx
  src/pages/CreateCompanyPage.tsx
  src/pages/CreatePostPage.tsx
  src/pages/CreateProfilePage.tsx
  src/pages/PostDetailPage.tsx
  src/pages/SignUpCompletePage.tsx
  src/shared/auth/ProtectedRoute.tsx
  src/shared/route/RouteNavigator.tsx
  src/shared/route/constants.ts
  src/shared/route/routeFormatPresentation.ts
  src/shared/route/useRouteNavigation.ts
  src/shared/route/useRouteParams.ts
Labels: feature

#407 ✨ 커피챗 목록 모든 성사, 거절 수정
  public/svg/badges.svg
  src/api/apis/localServer/apis.ts
  src/api/apis/localServer/schemas.ts
  src/components/button/CoffeeChatButton.tsx
  src/components/ui/badge.tsx
  src/components/ui/check.tsx
  src/components/ui/tabs.tsx
  src/entities/coffeeChat.ts
  src/feature/coffeeChat/service/coffeeChatService.ts
  src/feature/coffeeChat/ui/detail/ApplicantCoffeeChatDetailView.tsx
  src/feature/coffeeChat/ui/mypage/applicant/ApplicantCoffeeChatListView.tsx
  src/feature/coffeeChat/ui/mypage/common/CoffeeChatNumberBadge.tsx
  src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatListView.tsx
  src/mocks/coffeeChat/data.ts
  src/mocks/coffeeChat/handlers.ts
  src/mocks/coffeeChat/resolvers.ts
  src/mocks/coffeeChat/schemas.ts
Labels: refactor

#411 ✨ 인턴 공고 수정 페이지 생성 및 연결
  src/App.tsx
  src/entities/route.ts
  src/feature/auth/service/authService.ts
  src/feature/coffeeChat/ui/mypage/common/NoCoffeeChat.tsx
  src/feature/post/presentation/postFormPresentation.ts
  src/feature/post/ui/common/PostCard.tsx
  src/feature/post/ui/detail/PostDetailView.tsx
  src/feature/post/ui/form/PatchPostForm.tsx
  src/pages/CompanyMyPage.tsx
  src/pages/CreatePostPage.tsx
  src/shared/auth/AuthAdminSwitchRoute.tsx
  src/shared/auth/ProtectedRoute.tsx
  src/shared/context/RoleContext.ts
  src/shared/context/UserContext.ts
  src/shared/role/state.ts
  src/shared/route/useRouteNavigation.ts
Labels: feature

#413 💄 지원자 프로필 작성 폼 UI 수정
  src/App.tsx
  src/components/field/ExternalLinkField.tsx
  src/components/field/MultiStringField.tsx
  src/components/field/PdfField.tsx
  src/components/ui/separator.tsx
  src/entities/input.ts
  src/feature/applicant/presentation/applicantFormPresentation.ts
  src/feature/applicant/presentation/applicantInputPresentation.ts
  src/feature/applicant/ui/form/CreateProfileForm.tsx
  src/feature/applicant/ui/form/fields/DepartmentField.tsx
  src/feature/applicant/ui/mypage/ApplicantInfo.tsx
  src/feature/applicant/ui/mypage/SkeletonApplicantInfo.tsx
  src/feature/company/presentation/companyInputPresentation.ts
  src/feature/company/ui/form/CreateCompanyForm.tsx
  src/feature/company/ui/form/fields/SloganField.tsx
  src/feature/post/ui/detail/PostDetailView.tsx
Labels: feature

#415 💄 지원자 프로필이 없을 때의 ui 추가
  public/img/skeleton.png
  src/entities/asset.ts
  src/entities/errors.ts
  src/feature/applicant/ui/mypage/ApplicantInfo.tsx
  src/feature/applicant/ui/mypage/NoApplicantInfo.tsx
  src/pages/CreateProfilePage.tsx
  src/shared/route/useRouteNavigation.ts
  src/shared/route/useRouteParams.ts
Labels: bug

#419 👽️ Post 관련 API 수정사항 반영
  public/svg/location.svg
  src/api/apis/localServer/apis.ts
  src/api/apis/localServer/schemas.ts
  src/components/ui/badge.tsx
  src/entities/asset.ts
  src/entities/post.ts
  src/entities/route.ts
  src/feature/company/service/companyService.ts
  src/feature/post/service/postService.ts
  src/feature/post/ui/common/CompanyPostCard.tsx
  src/feature/post/ui/common/PostCard.tsx
  src/feature/post/ui/detail/PostDetailView.tsx
  src/feature/post/ui/form/CreatePostForm.tsx
  src/feature/post/ui/form/PatchPostForm.tsx
  src/feature/post/ui/landing/LandingPostView.tsx
  src/feature/post/ui/mypage/applicant/BookmarkListView.tsx
  src/feature/post/ui/mypage/company/MyPostList.tsx
  src/util/format.ts
Labels: refactor

#422 💄 회사 생성 폼 UI 생성
  package.json
  src/App.tsx
  src/api/apis/localServer/apis.ts
  src/api/apis/localServer/schemas.ts
  src/entities/company.ts
  src/entities/link.ts
  src/entities/post.ts
  src/entities/route.ts
  src/feature/applicant/presentation/applicantFormPresentation.ts
  src/feature/applicant/presentation/applicantInputPresentation.ts
  src/feature/applicant/service/applicantService.ts
  src/feature/applicant/ui/form/CreateProfileForm.tsx
  src/feature/company/presentation/companyFormPresentation.ts
  src/feature/company/presentation/companyInputPresentation.ts
  src/feature/company/service/companyService.ts
  src/feature/company/ui/form/CreateCompanyForm.tsx
  src/feature/company/ui/form/fields/LocationField.tsx
  src/feature/post/service/postService.ts
  src/feature/post/ui/form/fields/JobCategoryField.tsx
  src/mocks/applicant/schemas.ts
  src/pages/CreateCompanyPage.tsx
  src/util/format.ts
  src/util/postFormatFunctions.ts
  yarn.lock
Labels: feature

#424 [FEAT] GNB 구현
  public/svg/logo_icon.svg
  public/svg/logo_letter.svg
  public/svg/search.svg
  src/components/nav/GlobarNavigationBar.tsx
  src/components/ui/button.tsx
  src/entities/asset.ts
  src/feature/coffeeChat/ui/mypage/common/CoffeeChatNumberBadge.tsx
  src/pages/ApplicantMyPage.tsx
  src/pages/CompanyMyPage.tsx
Labels: feature

#427 ✨ 지원자 프로필 수정 기능 추가
  src/App.tsx
  src/api/apis/externalServer/apis.ts
  src/api/apis/externalServer/schemas.ts
  src/api/apis/localServer/schemas.ts
  src/api/client.ts
  src/components/button/DownloadButtonWithPresignedUrl.tsx
  src/feature/applicant/presentation/applicantFormPresentation.ts
  src/feature/applicant/presentation/applicantInputPresentation.ts
  src/feature/applicant/ui/form/CreateProfileForm.tsx
  src/feature/applicant/ui/form/PatchProfileForm.tsx
  src/feature/applicant/ui/form/SkeletonProfileForm.tsx
  src/feature/auth/service/authService.ts
  src/feature/auth/ui/findAccount/FindPasswordForm.tsx
  src/feature/auth/ui/signIn/ApplicantLocalLoginForm.tsx
  src/feature/auth/ui/signIn/CompanyLocalLoginForm.tsx
  src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  src/pages/CreateApplicantProfilePage.tsx
  src/pages/CreateProfilePage.tsx
  src/pages/PatchApplicantProfilePage.tsx
  src/shared/file/fileService.ts
  src/shared/file/hooks.ts
  src/shared/route/constants.ts
Labels: feature
