Repository wafflestudio/internhasha-web, pull requests merged in 2025-05, with the labels that each got.

#479 ✨ 구글 서치로 검색 불가능하도록 설정
  index.html
Labels: bug

#480 ✨ 모달 피그마와 동일하게 반영
  src/components/modal/CancelCheckModal.tsx
  src/components/modal/CancelCoffeeChatCancelModal.tsx
  src/components/modal/ClosePostModal.tsx
  src/components/modal/ReSignInModal.tsx
  src/components/modal/RewritePostModal.tsx
  src/components/modal/SignInForBookmarkModal.tsx
  src/components/modal/SignInForCoffeChatModal.tsx
  src/components/modal/SignUpModal.tsx
  src/components/modal/UpdateCoffeeChatStatusModal.tsx
  src/components/ui/layout.tsx
  src/feature/applicant/ui/modal/WithdrawModal.tsx
  src/feature/auth/ui/signUp/RedirectSignInModal.tsx
  src/feature/post/ui/modal/WriteCVModal.tsx
  src/feature/post/ui/modal/WriteProfileModal.tsx
  src/pages/ChangePasswordPage.tsx
  src/pages/EmailVerifyPage.tsx
  src/pages/ResetPasswordPage.tsx
  src/pages/SignUpCompletePage.tsx
  src/pages/SignUpPage.tsx
Labels: feature

#490 💄 프로필 뷰 및 생성페이지 반응형 추가
  src/components/field/MarkdownEditorField.tsx
  src/components/field/StringField.tsx
  src/components/field/TextareaField.tsx
  src/components/modal/CancelCheckModal.tsx
  src/components/modal/CancelCoffeeChatCancelModal.tsx
  src/components/modal/ClosePostModal.tsx
  src/components/modal/RewritePostModal.tsx
  src/components/modal/SignInForBookmarkModal.tsx
  src/components/modal/SignInForCoffeChatModal.tsx
  src/components/modal/SignUpModal.tsx
  src/components/modal/UpdateCoffeeChatStatusModal.tsx
  src/components/modal/WithdrawModal.tsx
  src/components/ui/layout.tsx
  src/feature/applicant/ui/form/CreateProfileForm.tsx
  src/feature/applicant/ui/mypage/ApplicantProfileInfo.tsx
  src/feature/applicant/ui/mypage/ApplicantProfileView.tsx
  src/feature/applicant/ui/mypage/NoApplicantInfo.tsx
  src/feature/coffeeChat/ui/mypage/applicant/ApplicantNoCoffeeChat.tsx
  src/feature/company/ui/mypage/CompanyProfileInfo.tsx
  src/feature/company/ui/mypage/CompanyProfileView.tsx
  src/feature/company/ui/mypage/NoCompanyProfile.tsx
  src/feature/company/ui/mypage/NoCreatedPosts.tsx
  src/pages/CreateApplicantProfilePage.tsx
  src/pages/CreateCoffeeChatPage.tsx
  src/pages/CreateCompanyPage.tsx
  src/pages/PatchApplicantProfilePage.tsx
  src/pages/PatchCompanyProfilePage.tsx
Labels: bug

#492 👽️ 직군 내용 변경 대응 및 필터 이름 변경 적용
  src/api/apis/localServer/schemas.ts
  src/entities/post.ts
  src/feature/post/service/postService.ts
  src/feature/post/ui/landing/LandingPageView.tsx
  src/feature/post/ui/landing/LandingPostView.tsx
  src/feature/post/ui/landing/RolesFilter.tsx
  src/mocks/post/schemas.ts
  src/util/format.ts
Labels: feature

#488 💄 커피챗 관련 설명 작성
  public/svg/edit_white.svg:Zone.Identifier
  src/feature/coffeeChat/ui/detail/ApplicantCoffeeChatDetailView.tsx
  src/feature/coffeeChat/ui/detail/ApplicantInfoForCoffeeChat.tsx
  src/feature/coffeeChat/ui/detail/CompanyCoffeeChatDetailView.tsx
  src/feature/coffeeChat/ui/mypage/applicant/ApplicantCoffeeChatListSkeleton.tsx
  src/feature/coffeeChat/ui/mypage/applicant/ApplicantCoffeeChatListView.tsx
  src/feature/coffeeChat/ui/mypage/common/CoffeeChatInfo.tsx
  src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatListView.tsx
  src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatListViewSkeleton.tsx
Labels: feature

#493 💄 마이페이지 탭 반응형 적용
  src/components/ui/tabs.tsx
  src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatButton.tsx
  src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatButtonGroup.tsx
  src/pages/ApplicantMyPage.tsx
  src/pages/CompanyMyPage.tsx
Labels: bug

#502 ✨ GNB 반응형 적용
  public/svg/hamburger-menu.svg
  src/components/nav/GlobalNavigationBar.tsx
  src/entities/asset.ts
Labels: feature

#515 💚 배포 인프라 변경에 따른 CD Workflow 수정
  .github/workflows/deploy-client.yml
  .github/workflows/deploy-dev.yml
Labels: refactor

#516 💚 버킷 이름 변경
  .github/workflows/deploy-client.yml
  .github/workflows/deploy-dev.yml
Labels: refactor

#508 🐛 파일 다운로드 시 이름 변경
  src/components/button/DownloadButtonWithPresignedUrl.tsx
  src/feature/applicant/ui/mypage/ApplicantProfileInfo.tsx
  src/feature/coffeeChat/ui/detail/ApplicantInfoForCoffeeChat.tsx
  src/feature/company/ui/mypage/CompanyProfileInfo.tsx
  src/feature/post/ui/detail/PostDetailView.tsx
  src/feature/post/ui/detail/SkeletonPostDetailView.tsx
  src/shared/file/hooks.ts
Labels: bug

#512 🐛 팝업 모달에 대한 반응형 추가
  src/components/ui/calendar.tsx
  src/feature/post/ui/form/CreatePostForm.tsx
  src/feature/post/ui/form/fields/EmploymentEndDateField.tsx
  src/feature/post/ui/form/fields/JobCategoryField.tsx
  src/feature/post/ui/form/fields/SalaryField.tsx
  src/pages/CreatePostPage.tsx
Labels: bug

#513 ✨ 회사 회원가입 관련 설명 및 약관 추가 & 푸터 추가
  src/components/field/TermsAgreeField.tsx
  src/components/footer/Footer.tsx
  src/components/modal/InformationTermModal.tsx
  src/components/modal/ServiceTermModal.tsx
  src/components/nav/GlobalNavigationBar.tsx
  src/components/ui/layout.tsx
  src/entities/agreements.ts
  src/feature/auth/presentation/authFormPresentation.ts
  src/feature/auth/presentation/authInputPresentation.ts
  src/feature/auth/ui/signUp/LocalSignUpForm.tsx
  src/pages/ApplicantCoffeeChatDetailPage.tsx
  src/pages/ApplicantMyPage.tsx
  src/pages/CompanyCoffeeChatDetailPage.tsx
  src/pages/CompanyMyPage.tsx
  src/pages/CreateApplicantProfilePage.tsx
  src/pages/CreateCoffeeChatPage.tsx
  src/pages/CreateCompanyPage.tsx
  src/pages/CreatePostPage.tsx
  src/pages/LandingPage.tsx
  src/pages/PatchApplicantProfilePage.tsx
  src/pages/PatchCompanyProfilePage.tsx
  src/pages/PostDetailPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/shared/route/constants.ts
Labels: feature

#519 🚑 vite proxy에서 변경된 와플 인프라 적용
  .env.dev
  .env.prod
  index.html
  vite.config.ts
Labels: bug

#517 🐛공고 관련 QA 반영
  src/api/apis/localServer/schemas.ts
  src/components/modal/ClosePostModal.tsx
  src/entities/route.ts
  src/feature/post/presentation/postFormPresentation.ts
  src/feature/post/ui/detail/PostDetailView.tsx
  src/feature/post/ui/form/CreatePostForm.tsx
  src/feature/post/ui/form/PatchPostForm.tsx
  src/feature/post/ui/form/fields/SalaryField.tsx
Labels: bug

#521 ✨ 로그인, 회원가입, 모달 반응형 적용
  src/components/ui/layout.tsx
  src/components/ui/tabs.tsx
  src/feature/auth/ui/fields/PasswordConfirmField.tsx
  src/feature/auth/ui/fields/PasswordField.tsx
  src/feature/auth/ui/fields/PasswordFieldWithDetailedError.tsx
  src/feature/auth/ui/signUp/EmailVerifyForm.tsx
Labels: feature

#523 ✨ 회사회원 나에게 신청된 커피챗 탭에서 ‘선택하기’ 누를 시 탭 overflow 및 경고 해결
  src/components/button/CoffeeChatButton.tsx
  src/components/ui/tabs.tsx
  src/feature/coffeeChat/ui/mypage/common/CoffeeChatNumberBadge.tsx
  src/feature/coffeeChat/ui/mypage/company/CompanyCoffeeChatButtonGroup.tsx
  src/pages/CompanyMyPage.tsx
  src/pages/SignInPage.tsx
Labels: bug

#525 💄 마크다운 에디터 변경 및 이미지 업로드 기능 삭제
  package.json
  src/components/field/MarkdownEditorField.tsx
  src/components/ui/markdown-preview.tsx
  src/index.css
  tsconfig.json
  yarn.lock
Labels: feature

#527 💄 약관 모달, 캘린더 모달, 작성한 공고, 공고 상세 페이지 반응형 수정 및 이메일 전송 이후 "인증코드 전송하기" 버튼 비활성화
  src/components/button/LinkButton.tsx
  src/components/field/TermsAgreeField.tsx
  src/components/information/Information.tsx
  src/components/modal/InformationTermModal.tsx
  src/components/modal/ServiceTermModal.tsx
  src/components/ui/calendar.tsx
  src/components/ui/layout.tsx
  src/components/ui/tabs.tsx
  src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  src/feature/coffeeChat/ui/detail/ApplicantCoffeeChatDetailView.tsx
  src/feature/coffeeChat/ui/detail/CompanyCoffeeChatDetailView.tsx
  src/feature/coffeeChat/ui/mypage/applicant/ApplicantNoCoffeeChat.tsx
  src/feature/coffeeChat/ui/mypage/common/CoffeeChatInfo.tsx
  src/feature/company/ui/mypage/NoCompanyProfile.tsx
  src/feature/company/ui/mypage/NoCreatedPosts.tsx
  src/feature/post/ui/common/CompanyPostCard.tsx
  src/feature/post/ui/detail/PostDetailView.tsx
  src/feature/post/ui/form/PatchPostForm.tsx
  src/feature/post/ui/form/fields/EmploymentEndDateField.tsx
  src/feature/post/ui/mypage/applicant/NoBookmarkedPosts.tsx
  src/pages/ApplicantMyPage.tsx
  src/pages/CompanyMyPage.tsx
  src/pages/SignUpPage.tsx
Labels: bug

#530 👽️ 이력서 작성 필수화
  src/api/apis/localServer/schemas.ts
  src/components/modal/WriteProfileModal.tsx
  src/feature/applicant/presentation/applicantFormPresentation.ts
  src/feature/applicant/service/applicantService.ts
  src/feature/applicant/ui/form/CreateProfileForm.tsx
  src/feature/applicant/ui/mypage/ApplicantProfileInfo.tsx
  src/feature/coffeeChat/ui/detail/ApplicantInfoForCoffeeChat.tsx
  src/feature/post/ui/detail/PostDetailView.tsx
  src/feature/post/ui/modal/WriteCVModal.tsx
  src/mocks/applicant/schemas.ts
Labels: feature

#531 🐛 메인페이지 및 커피챗 오류
  src/components/ui/popover.tsx
  src/feature/coffeeChat/ui/detail/ApplicantCoffeeChatDetailView.tsx
  src/feature/coffeeChat/ui/detail/CompanyCoffeeChatDetailView.tsx
  src/feature/post/ui/landing/FilterSection.tsx
Labels: bug

#539 🐛 공고 생성 페이지에서 인원에 대한 안내 추가
  src/feature/post/presentation/postFormPresentation.ts
  src/feature/post/ui/detail/PostDetailView.tsx
  src/feature/post/ui/form/CreatePostForm.tsx
Labels: bug

#542 ✨ 커피챗 상세 페이지에서 성사 및 거절 시 모달 추가
  src/components/modal/UpdateCoffeeChatStatusModal.tsx
  src/feature/coffeeChat/ui/detail/CompanyCoffeeChatDetailView.tsx
Labels: feature

#559 🐛 폼 관련 에러 메세지 내용 및 배치 수정
  src/feature/applicant/ui/form/CreateProfileForm.tsx
  src/feature/coffeeChat/ui/form/CreateCoffeeChatForm.tsx
  src/feature/company/presentation/companyFormPresentation.ts
  src/feature/company/ui/form/CreateCompanyForm.tsx
  src/feature/post/ui/form/CreatePostForm.tsx
Labels: bug

#557 ✨ 공고 카드에 직군 정보가 추가
  src/api/apis/localServer/schemas.ts
  src/entities/post.ts
  src/feature/post/ui/common/PostCard.tsx
Labels: feature

#569 💄 필터 중 공고 등록순으로 이름 변경
  src/feature/post/ui/landing/FilterSection.tsx
Labels: bug

#560 🐛 북마크 적용 시 Optimistic Updates
  src/feature/post/ui/common/PostCard.tsx
  src/feature/post/ui/detail/PostDetailView.tsx
  src/feature/post/ui/landing/LandingPostView.tsx
Labels: bug

#566 🐛 메일 중복 인증 확인 로직 추가
  src/feature/auth/service/authService.ts
  src/feature/auth/ui/signUp/EmailVerifyForm.tsx
Labels: bug

#567 🐛 페이지네이션 시 쿼리 파라미터 반영 및 disble 적용
  src/components/ui/pagination.tsx
  src/feature/post/ui/landing/LandingPostView.tsx
  src/feature/post/ui/landing/PaginationBar.tsx
  src/mocks/post/data.ts
  src/mocks/post/handlers.ts
  src/mocks/post/resolvers.ts
  src/mocks/post/schemas.ts
  src/pages/LandingPage.tsx
Labels: bug

#568 ✨ 푸터에 버그 제보용 구글폼 추가
  src/components/footer/Footer.tsx
Labels: feature

#577 🐛 모바일에서 외부 링크 부분 스타일링 깨지는 부분 수정
  src/feature/post/ui/detail/PostDetailView.tsx
Labels: bug

#575 ✨ 공유하기 링크 추가 및 오픈그래프 이미지 적용
  index.html
  public/og/intern_hasha_opengraph.png
  src/components/button/LinkCopyButton.tsx
  src/feature/post/ui/detail/PostDetailView.tsx
Labels: feature
