Repository wafflestudio/internhasha-web, pull requests merged in 2025-01, with the labels that each got.

#41 ✨구글 소셜 회원가입 기능 추가
  package.json
  src/App.tsx
  src/entities/route.ts
  src/main.tsx
  src/pages/EmailVerifyPage/index.tsx
  src/pages/SignUpPage/GoogleSocialSignUpForm.tsx
  src/pages/SignUpPage/LocalSignUpForm.tsx
  src/pages/SignUpPage/SignUpForm.tsx
  src/pages/SignUpPage/index.tsx
  src/presentation/authPresentation.ts
  src/service/authService.ts
  src/shared/api/api.ts
  src/shared/api/entities/schemas.ts
  src/shared/context/EnvContext.ts
  src/shared/route/useRouteNavigation.ts
  src/vite-env.d.ts
  yarn.lock
Labels: feature

#47 ✨ 구글 소셜 로그인 추가
  src/App.tsx
  src/entities/route.ts
  src/pages/LandingPage/index.tsx
  src/pages/LocalSignInPage/LogInForm.tsx
  src/pages/LocalSignInPage/index.tsx
  src/pages/SignInSelectPage/GoogleSocialSignInButton.tsx
  src/pages/SignInSelectPage/index.tsx
  src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
  src/pages/SignUpSelectPage/index.tsx
  src/service/authService.ts
  src/shared/api/api.ts
  src/shared/api/entities/schemas.ts
  src/shared/route/useRouteNavigation.ts
Labels: feature

#51 ✨ 로그인 플로우 및 스키마 변경
  src/App.tsx
  src/entities/route.ts
  src/pages/LocalSignInPage/index.tsx
  src/pages/LocalSignUpPage/LocalSignUpForm.tsx
  src/pages/SignInSelectPage/GoogleSocialSignInButton.tsx
  src/pages/SignInSelectPage/LogInForm.tsx
  src/pages/SignInSelectPage/index.tsx
  src/presentation/authPresentation.ts
  src/service/authService.ts
  src/shared/api/api.ts
  src/shared/api/entities/schemas.ts
  src/shared/route/useRouteNavigation.ts
Labels: feature

#53 ✨ 구글 소셜 회원가입 플로우 및 스키마 수정
  .env.dev
  src/components/form/FormContainer.tsx
  src/entities/user.ts
  src/mocks/auth/data.ts
  src/mocks/auth/handlers.ts
  src/mocks/auth/resolvers.ts
  src/mocks/auth/schemas.ts
  src/mocks/handlers.ts
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  src/pages/EmailVerifyPage/index.tsx
  src/pages/LocalSignUpPage/LocalSignUpForm.tsx
  src/pages/SignInSelectPage/GoogleSocialSignInButton.tsx
  src/pages/SignInSelectPage/LogInForm.tsx
  src/service/authService.ts
  src/shared/api/api.ts
  src/shared/api/entities/schemas.ts
  src/util/format.ts
Labels: feature

#49 [FEAT] 게시판 리스트 mock api 작성하기
  src/App.tsx
  src/mocks/echo/resolvers.ts
  src/mocks/handlers.ts
  src/mocks/post/handlers.ts
  src/mocks/post/resolvers.ts
  src/mocks/post/schemas.ts
  src/pages/LandingPage/index.tsx
  src/service/postService.ts
  src/shared/api/api.ts
  src/shared/api/entities/schemas.ts
  src/shared/context/ServiceContext.ts
Labels: feature

#58 ✨ 로컬 회원가입 유저 플로우 및 스키마 수정
  src/mocks/auth/handlers.ts
  src/mocks/auth/resolvers.ts
  src/mocks/auth/schemas.ts
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  src/pages/LocalSignUpPage/LocalSignUpForm.tsx
  src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
  src/presentation/authPresentation.ts
  src/service/authService.ts
  src/shared/api/api.ts
  src/shared/api/entities/schemas.ts
  src/shared/route/useRouteNavigation.ts
Labels: feature

#59 🚑 gitignore된 .env 정보 추가
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
Labels: bug

#60 Fix/#56/yeonu kim
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
Labels: bug

#61 🚑 CI 세팅에서 secret 이름 수정
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
Labels: bug

#62 🔥 불필요한 CI 디버그 echo 제거
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  README.md
Labels: bug

#64 ✨ 화면 명세 중 로컬 회원가입 조건 반영
  src/components/input/LabelContainer.tsx
  src/components/input/TextInput.tsx
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  src/pages/LocalSignUpPage/LocalSignUpForm.tsx
  src/presentation/authPresentation.ts
Labels: feature

#71 ✨ 무효한 토큰 발생 시 refresh 시행 및 재로그인 유도 모달 뜨도록 설정
  src/App.tsx
  src/components/modal/ReSignInModal.tsx
  src/entities/route.ts
  src/entities/user.ts
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  src/pages/LandingPage/index.tsx
  src/pages/MyPage/index.tsx
  src/service/authService.ts
  src/service/userService.ts
  src/shared/api/api.ts
  src/shared/api/entities/schemas.ts
  src/shared/auth/AuthProtectedRoute.tsx
  src/shared/context/ServiceContext.ts
  src/shared/token/localstorage.ts
Labels: feature

#66 ✨ 이메일 인증 페이지 유저 플로우 반영
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  src/pages/LocalSignUpPage/LocalSignUpForm.tsx
  src/pages/SignInSelectPage/LogInForm.tsx
  src/pages/SignUpSelectPage/index.tsx
  src/presentation/authPresentation.ts
  src/shared/route/useRouteNavigation.ts
Labels: feature

#72 ✨ progress bar 로컬 회원가입에만 적용
  src/components/progressBar/ProgressBar.tsx
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  src/pages/LocalSignUpPage/LocalSignUpForm.tsx
Labels: feature

#74 ✨ 회원가입 시 버튼 disable 설정
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  src/pages/LocalSignUpPage/LocalSignUpForm.tsx
Labels: feature

#78 🚑 마이페이지 url 변경
  src/shared/api/api.ts
Labels: bug

#80 🐛 이메일 input에서 @snu.ac.kr 제거
  src/components/input/TextInput.tsx
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  src/pages/LocalSignUpPage/LocalSignUpForm.tsx
  src/presentation/authPresentation.ts
Labels: bug

#83 🐛 implicit 대신 auth code 방식으로 변경
  src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
Labels: refactor

#57 [FEAT] post 관련 api 기능 로직 작성하기
  src/App.tsx
  src/entities/route.ts
  src/mocks/post/handlers.ts
  src/mocks/post/resolvers.ts
  src/mocks/post/schemas.ts
  src/pages/LandingPage/PostPage/index.tsx
  src/pages/LandingPage/index.tsx
  src/service/postService.ts
  src/shared/api/api.ts
  src/shared/api/entities/schemas.ts
  src/shared/route/useRouteNavigation.ts
Labels: feature

#86 [FEAT] post, postid mock api 작성
  src/entities/route.ts
  src/mocks/post/data.ts
  src/mocks/post/handlers.ts
  src/mocks/post/resolvers.ts
  src/mocks/post/schemas.ts
  src/pages/LandingPage/PostPage/index.tsx
  src/pages/LandingPage/index.tsx
Labels: feature

#89 🚑 잘못된 access token이 전달되는 현상 수정
  src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
Labels: bug

#90 ✨ 통합 회원가입 기능 생성
  src/entities/response.ts
  src/mocks/auth/resolvers.ts
  src/mocks/auth/schemas.ts
  src/pages/EmailVerifyPage/AddSignUpModal.tsx
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
  src/service/authService.ts
  src/service/echoService.ts
  src/service/postService.ts
  src/service/userService.ts
  src/shared/api/api.ts
  src/shared/api/entities/params.ts
Labels: feature

#111 ✨ 이름 무효 시 하단에 경고 메세지 나타나도록 설정
  src/pages/LandingPage/PostCard.tsx
  src/pages/LocalSignUpPage/LocalSignUpForm.tsx
  src/shared/api/entities/schemas.ts
Labels: feature

#115 🐛 이메일 인증 시 conflict 발생 이후 모달 띄우기
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
Labels: bug

#116 🐛 코드 전송 시 모달 나타나도록 수정
  src/pages/EmailVerifyPage/EmailVerifyForm.tsx
Labels: bug

#118 🐛 post 스키마 중 employeeEndDate를 employmentEndDate로 변경
  src/pages/LandingPage/PostCard.tsx
  src/pages/LandingPage/PostPage/index.tsx
  src/shared/api/entities/schemas.ts
Labels: bug

#122 👷 분리 배포를 위한 CI 생성
  .github/workflows/deploy-admin.yml
  .github/workflows/deploy-client.yml
Labels: feature

#124 💚 태그 푸시 대신 메인에 머지되면 배포되도록 변경
  .github/workflows/deploy-admin.yml
  .github/workflows/deploy-client.yml
  apps/client/package.json
  package.json
Labels: refactor

#135 🔥 .env.local 삭제 및 .idea gitignore에 추가
  .env.local
  .gitignore
  .idea/.gitignore
  .idea/22-5-team1-web.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/prettier.xml
  .idea/vcs.xml
Labels: bug

#137 ✨ 디자인 시스템 패키지 생성
  .pnp.cjs
  .yarn/cache/@eslint-config-array-npm-0.19.1-2985276432-43b01f596d.zip
  .yarn/cache/@eslint-js-npm-9.18.0-a952cf1b19-3938344c5a.zip
  .yarn/cache/@humanwhocodes-retry-npm-0.4.1-44b0ee0d64-be7bb6841c.zip
  .yarn/cache/@types-react-dom-npm-18.3.5-b1c4b786e6-b163d35a6b.zip
  .yarn/cache/@types-react-npm-18.3.18-2cfc7440b2-8fb2b00672.zip
  .yarn/cache/@typescript-eslint-eslint-plugin-npm-8.19.1-b2a3ac2e78-993784b045.zip
  .yarn/cache/@typescript-eslint-parser-npm-8.19.1-934b08a27a-1afbd2d0a2.zip
  .yarn/cache/@typescript-eslint-scope-manager-npm-8.19.1-da457e6eb8-7dca0c28ad.zip
  .yarn/cache/@typescript-eslint-type-utils-npm-8.19.1-2ad87106a6-757592b515.zip
  .yarn/cache/@typescript-eslint-types-npm-8.19.1-90bcc34378-e907bf096d.zip
  .yarn/cache/@typescript-eslint-typescript-estree-npm-8.19.1-90782c2bb1-549d9d565a.zip
  .yarn/cache/@typescript-eslint-utils-npm-8.19.1-497e6fd802-f7d2fe9a2b.zip
  .yarn/cache/@typescript-eslint-visitor-keys-npm-8.19.1-29b3acecde-117537450a.zip
  .yarn/cache/@vitejs-plugin-react-swc-npm-3.7.2-9b9d5c642b-9b9a5e0540.zip
  .yarn/cache/esbuild-npm-0.24.2-0dcfc14be5-5a25bb08b6.zip
  .yarn/cache/eslint-npm-9.18.0-6a3f949ad6-7f592ad228.zip
  .yarn/cache/eslint-plugin-react-hooks-npm-5.1.0-cc261f8c02-37ef76e1d9.zip
  .yarn/cache/eslint-plugin-react-refresh-npm-0.4.18-3857cb5d46-19140a0d90.zip
  .yarn/cache/globals-npm-15.14.0-1cb78aecb8-039deb8648.zip
  .yarn/cache/ts-api-utils-npm-2.0.0-1384745dce-6165e29a5b.zip
  .yarn/cache/typescript-eslint-npm-8.19.1-aa16efe238-59cdb590a0.zip
  .yarn/cache/vite-npm-6.0.7-8c24f1f180-ae81047b42.zip
  apps/admin/package.json
  apps/admin/src/App.tsx
  packages/design-system/.gitignore
  packages/design-system/.prettierignore
  packages/design-system/README.md
  packages/design-system/eslint.config.js
  packages/design-system/package.json
  packages/design-system/src/Button/Button.tsx
  packages/design-system/src/Button/SubmitButton.tsx
  packages/design-system/src/Button/index.tsx
  packages/design-system/src/index.ts
  packages/design-system/tsconfig.json
  packages/design-system/vite.config.ts
  packages/eslint-react/.prettierignore
  packages/math/.gitignore
  packages/math/package.json
  packages/math/src/index.ts
  packages/math/tsconfig.json
  yarn.lock
Labels: feature

#142 🚑 CI 변경되지 않는 부분 수정
  .github/workflows/deploy-admin.yml
  .github/workflows/deploy-client.yml
Labels: bug

#143 ♻️ 빌드 대신 직접 src에서 import하도록 수정
  apps/admin/package.json
  apps/client/package.json
  packages/design-system/package.json
  packages/eslint-react/package.json
  packages/eslint-react/src/index.js
  packages/eslint-react/tsconfig.json
Labels: refactor

#147 ✨ 디자인 시스템에 테일윈드 설정 완료
  .pnp.cjs
  apps/admin/package.json
  apps/admin/postcss.config.js
  apps/admin/src/App.tsx
  apps/admin/src/index.css
  apps/admin/src/reset.css
  apps/admin/tailwind.config.js
  apps/admin/vite.config.ts
  apps/client/package.json
  apps/client/postcss.config.js
  apps/client/src/App.tsx
  apps/client/src/index.css
  apps/client/src/pages/LandingPage/index.tsx
  apps/client/tailwind.config.js
  packages/design-system/package.json
  packages/design-system/src/Button/Button.tsx
  packages/design-system/src/index.tsx
  yarn.lock
Labels: feature

#149 ✨ api 패키지 생성
  .pnp.cjs
  apps/admin/.env.dev
  apps/admin/.env.mock
  apps/admin/.env.prod
  apps/admin/package.json
  apps/admin/src/App.tsx
  apps/admin/src/entities/echo.ts
  apps/admin/src/entities/response.ts
  apps/admin/src/services/echoService.ts
  apps/admin/src/vite-env.d.ts
  apps/admin/tsconfig.json
  apps/admin/vite.config.ts
  apps/client/vite.config.ts
  packages/api/.gitignore
  packages/api/package.json
  packages/api/src/api.ts
  packages/api/src/client.ts
  packages/api/src/entities/index.ts
  packages/api/src/entities/params.ts
  packages/api/src/entities/schemas.ts
  packages/api/src/index.ts
  packages/api/tsconfig.json
  yarn.lock
Labels: feature

#151 ✨어드민 페이지 라우터 및 토큰 설정
  .pnp.cjs
  apps/admin/package.json
  apps/admin/src/App.tsx
  apps/admin/src/components/modal/ReSignInModal.tsx
  apps/admin/src/entities/route.ts
  apps/admin/src/entities/user.ts
  apps/admin/src/feature/auth/index.ts
  apps/admin/src/feature/auth/presentation/authPresentation.ts
  apps/admin/src/feature/auth/service/authService.ts
  apps/admin/src/feature/auth/ui/LoginForm.tsx
  apps/admin/src/feature/echo/index.tsx
  apps/admin/src/feature/echo/presentation/echoPresentation.ts
  apps/admin/src/feature/echo/service/echoService.ts
  apps/admin/src/feature/echo/ui/MessageUppercaseConverter.tsx
  apps/admin/src/feature/user/index.tsx
  apps/admin/src/feature/user/service/userService.ts
  apps/admin/src/feature/user/ui/MyInfo.tsx
  apps/admin/src/main.tsx
  apps/admin/src/pages/EchoPage.tsx
  apps/admin/src/pages/LandingPage.tsx
  apps/admin/src/pages/LoginPage.tsx
  apps/admin/src/pages/MyPage.tsx
  apps/admin/src/shared/auth/AuthProtectedRoute.tsx
  apps/admin/src/shared/context/EnvContext.ts
  apps/admin/src/shared/context/ServiceContext.ts
  apps/admin/src/shared/context/TokenContext.ts
  apps/admin/src/shared/context/hooks.ts
  apps/admin/src/shared/route/useRouteNavigation.ts
  apps/admin/src/shared/token/tokenLocalStorageRepository.ts
  apps/admin/src/shared/token/tokenStateRepository.ts
  packages/design-system/src/form/FormContainer.tsx
  packages/design-system/src/form/index.tsx
  packages/design-system/src/index.tsx
  packages/design-system/src/input/LabelContainer.tsx
  packages/design-system/src/input/TextInput.tsx
  packages/design-system/src/input/index.tsx
  packages/design-system/src/progressBar/ProgressBar.tsx
  packages/design-system/src/progressBar/index.tsx
  yarn.lock
Labels: feature

#153 ✨디자인시스템 패키지에 cva 적용
  .pnp.cjs
  apps/admin/tailwind.config.js
  packages/design-system/eslint.config.js
  packages/design-system/package.json
  packages/design-system/src/Button/Button.tsx
  packages/design-system/src/utils/merge.ts
  yarn.lock
Labels: feature

#156 ✨ post 생성 스켈레톤 코드 작성
  apps/admin/src/App.tsx
  apps/admin/src/entities/input.ts
  apps/admin/src/entities/route.ts
  apps/admin/src/feature/auth/presentation/authPresentation.ts
  apps/admin/src/feature/post/index.tsx
  apps/admin/src/feature/post/presentation/postPresentation.ts
  apps/admin/src/feature/post/ui/CreateCompanyForm.tsx
  apps/admin/src/feature/post/ui/CreatePostForm.tsx
  apps/admin/src/pages/CreateCompanyPage.tsx
  apps/admin/src/pages/CreatePostPage.tsx
  apps/admin/src/shared/route/useRouteNavigation.ts
Labels: feature

#160 ✨ 회사 생성 페이지 생성
  apps/admin/src/entities/input.ts
  apps/admin/src/feature/post/presentation/companypresentation.ts
  apps/admin/src/feature/post/presentation/postPresentation.ts
  apps/admin/src/feature/post/ui/CreateCompanyForm.tsx
  packages/design-system/src/Button/Button.tsx
Labels: feature

#166 ✨ 회원가입 및 로그인 DTO 수정 사항 반영
  .pnp.cjs
  apps/admin/src/feature/auth/service/authService.ts
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/entities/author.ts
  apps/client/src/entities/paginator.ts
  apps/client/src/entities/post.ts
  apps/client/src/entities/resume.ts
  apps/client/src/pages/EmailVerifyPage/AddSignUpModal.tsx
  apps/client/src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  apps/client/src/pages/LandingPage/PostCard.tsx
  apps/client/src/pages/SignInSelectPage/GoogleSocialSignInButton.tsx
  apps/client/src/pages/SignInSelectPage/LogInForm.tsx
  apps/client/src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
  apps/client/src/service/authService.ts
  apps/client/src/service/echoService.ts
  apps/client/src/service/postService.ts
  apps/client/src/service/resumeService.ts
  apps/client/src/service/userService.ts
  apps/client/src/shared/api/api.ts
  apps/client/src/shared/api/client.ts
  apps/client/src/shared/api/entities/index.ts
  apps/client/src/shared/api/entities/params.ts
  apps/client/src/shared/api/entities/schemas.ts
  apps/client/src/shared/api/index.ts
  packages/api/eslint.config.js
  packages/api/package.json
  packages/api/src/api.ts
  packages/api/src/entities/schemas.ts
  yarn.lock
Labels: feature

#173 ✨ 회사 권한이 없는 사람은 회사 페이지를 들어갈 수 없도록 설정
  .pnp.cjs
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/entities/decodedToken.ts
  apps/client/src/shared/auth/CompanyProtectedRoute.tsx
  apps/client/src/shared/route/RouteNavigator.tsx
  packages/design-system/package.json
  yarn.lock
Labels: feature

#176 ✨ 채용 공고 및 회사 정보 작성 시 엣지 케이스 방어
  apps/client/src/App.tsx
  apps/client/src/entities/input.ts
  apps/client/src/feature/post/presentation/companypresentation.ts
  apps/client/src/feature/post/presentation/postPresentation.ts
  apps/client/src/feature/post/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
Labels: feature

#179 ✨ company 생성 페이지에 백엔드 API 적용
  apps/client/src/App.tsx
  apps/client/src/components/modal/CancelCheckModal.tsx
  apps/client/src/entities/post.ts
  apps/client/src/feature/post/index.tsx
  apps/client/src/feature/post/presentation/companypresentation.ts
  apps/client/src/feature/post/service/postService.ts
  apps/client/src/feature/post/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/mocks/handlers.ts
  apps/client/src/mocks/post/data.ts
  apps/client/src/mocks/post/handlers.ts
  apps/client/src/mocks/post/resolvers.ts
  apps/client/src/mocks/resume/handlers.ts
  apps/client/src/mocks/resume/resolvers.ts
  apps/client/src/pages/EmailVerifyPage/EmailVerifyForm.tsx
  apps/client/src/pages/LandingPage/CoffeeChatListPage/CoffeeChatDetailPage/index.tsx
  apps/client/src/pages/LandingPage/CoffeeChatListPage/index.tsx
  apps/client/src/pages/LandingPage/FilterSection.tsx
  apps/client/src/pages/LandingPage/PostPage/index.tsx
  apps/client/src/pages/LandingPage/index.tsx
  apps/client/src/pages/LocalSignUpPage/LocalSignUpForm.tsx
  apps/client/src/pages/SignUpSelectPage/GoogleSocialSignUpButton.tsx
  apps/client/src/pages/SignUpSelectPage/index.tsx
  apps/client/src/shared/context/ServiceContext.ts
  apps/client/src/shared/route/useRouteNavigation.ts
  packages/api/src/apis/externalServer/apis.ts
  packages/api/src/apis/externalServer/index.ts
  packages/api/src/apis/externalServer/schemas.ts
  packages/api/src/apis/index.ts
  packages/api/src/apis/localServer/apis.ts
  packages/api/src/apis/localServer/index.ts
  packages/api/src/apis/localServer/schemas.ts
  packages/api/src/client.ts
  packages/api/src/entities/index.ts
  packages/api/src/entities/params.ts
  packages/api/src/index.ts
Labels: feature

#181 ✨ post 생성 api와 연결
  apps/client/src/entities/post.ts
  apps/client/src/feature/post/presentation/companypresentation.ts
  apps/client/src/feature/post/presentation/postPresentation.ts
  apps/client/src/feature/post/service/postService.ts
  apps/client/src/feature/post/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/pages/LandingPage/FilterSection.tsx
  apps/client/src/shared/route/useRouteNavigation.ts
  packages/api/src/apis/localServer/schemas.ts
Labels: feature

#183 ✨ 마크다운 에디터 적용
  .pnp.cjs
  apps/client/package.json
  apps/client/src/feature/post/presentation/postPresentation.ts
  apps/client/src/feature/post/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  yarn.lock
Labels: feature

#185 ✨ vc 로그인 시 vc 전용 랜딩 페이지가 나타나도록 수정
  apps/client/src/App.tsx
  apps/client/src/feature/ventureCapital/index.tsx
  apps/client/src/feature/ventureCapital/ui/MyCompanyList.tsx
  apps/client/src/feature/ventureCapital/ui/MyPage.tsx
  apps/client/src/feature/ventureCapital/ui/MyPostList.tsx
  apps/client/src/feature/ventureCapital/ui/VentureCapitalLandingTab.tsx
  apps/client/src/pages/VentureCapitalLandingPage.tsx
  apps/client/src/shared/auth/AuthAdminSwitchRoute.tsx
Labels: feature

#189 💄 로그인 페이지 스타일링
  .pnp.cjs
  apps/client/components.json
  apps/client/index.html
  apps/client/package.json
  apps/client/src/components/form/FormContainer.tsx
  apps/client/src/components/ui/button.tsx
  apps/client/src/components/ui/input.tsx
  apps/client/src/components/ui/label.tsx
  apps/client/src/components/ui/layout.tsx
  apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
  apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
  apps/client/src/index.css
  apps/client/src/lib/utils.ts
  apps/client/src/pages/SignInSelectPage.tsx
  apps/client/tailwind.config.js
  yarn.lock
Labels: feature

#191 💄 회원가입 페이지 스타일링
  apps/client/public/img/google_icon.png
  apps/client/src/entities/asset.ts
  apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
  apps/client/src/feature/auth/ui/signUp/GoogleSocialSignUpButton.tsx
  apps/client/src/pages/SignInSelectPage.tsx
  apps/client/src/pages/SignUpSelectPage.tsx
Labels: feature

#198 🚑 mockServiceWorker 빌드 시 삭제
  .github/workflows/deploy-client.yml
  .pnp.cjs
  apps/client/.gitignore
  apps/client/tsconfig.tsbuildinfo
Labels: bug

#203 ✨ 로그인 및 회원가입 DTO 변경사항 수정
  apps/client/src/components/form/FormContainer.tsx
  apps/client/src/entities/author.ts
  apps/client/src/entities/errors.ts
  apps/client/src/entities/post.ts
  apps/client/src/entities/response.ts
  apps/client/src/entities/resume.ts
  apps/client/src/entities/user.ts
  apps/client/src/feature/auth/service/authService.ts
  apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
  apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
  apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  apps/client/src/feature/auth/ui/signUp/GoogleSocialSignUpButton.tsx
  apps/client/src/feature/post/service/postService.ts
  apps/client/src/feature/resume/service/resumeService.ts
  apps/client/src/feature/resume/ui/ResumeList.tsx
  apps/client/src/feature/user/service/userService.ts
  apps/client/src/feature/user/ui/MyInfo.tsx
  apps/client/src/shared/file/fileService.ts
  packages/api/src/apis/localServer/schemas.ts
  packages/api/src/entities/index.ts
Labels: feature

#204 💄 로컬 회원가입 페이지 스타일링
  apps/client/public/svg/check.svg
  apps/client/public/svg/close.svg
  apps/client/src/components/form/FormContainer.tsx
  apps/client/src/components/input/LabelContainer.tsx
  apps/client/src/components/response/formError.tsx
  apps/client/src/components/ui/input.tsx
  apps/client/src/entities/asset.ts
  apps/client/src/entities/errors.ts
  apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
  apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
  apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  apps/client/src/feature/auth/ui/signUp/GoogleSocialSignUpButton.tsx
  apps/client/src/feature/auth/ui/signUp/LocalSignUpForm.tsx
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/landing/ui/PostCard.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/pages/LocalSignUpPage.tsx
  apps/client/tailwind.config.js
  apps/client/tsconfig.tsbuildinfo
Labels: feature

#206 💄 이메일 인증 페이지 스타일링
  apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  apps/client/src/pages/EmailVerifyPage.tsx
Labels: feature

#208 💄 회원가입 완료 페이지 및 모달 스타일링
  apps/client/src/components/form/FormContainer.tsx
  apps/client/src/components/progressBar/ProgressBar.tsx
  apps/client/src/components/ui/layout.tsx
  apps/client/src/feature/auth/ui/signUp/AddSignUpModal.tsx
  apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  apps/client/src/pages/LocalSignUpPage.tsx
  apps/client/src/pages/SignUpCompletePage.tsx
Labels: feature

#210 🐛 회원가입 시 conflict에 따라 모달이 정상적으로 나타나도록 수정
  apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  packages/api/src/apis/localServer/schemas.ts
Labels: bug

#213 ♻️ setResponseMessage에서 에러 코드 대신 에러 메세지를 넣도록 수정
  apps/client/src/entities/errors.ts
  apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
  apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
  apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  apps/client/src/feature/auth/ui/signUp/GoogleSocialSignUpButton.tsx
  apps/client/src/feature/auth/ui/signUp/LocalSignUpForm.tsx
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
Labels: refactor

#215 ♻️ roles filter가 service-repository 구조를 갖추도록 리팩토링
  apps/client/src/App.tsx
  apps/client/src/entities/filter.ts
  apps/client/src/feature/auth/service/authService.ts
  apps/client/src/feature/landing/hooks/useGetPosts.ts
  apps/client/src/feature/landing/service/landingService.ts
  apps/client/src/feature/landing/ui/FilterSection.tsx
  apps/client/src/feature/landing/ui/PostCard.tsx
  apps/client/src/feature/landing/ui/RolesFilter.tsx
  apps/client/src/feature/post/service/postService.ts
  apps/client/src/pages/LandingPage.tsx
  apps/client/src/shared/context/RolesFilterContext.tsx
  apps/client/src/shared/context/ServiceContext.ts
  apps/client/src/shared/rolesFilter/localstorage.ts
  apps/client/src/shared/rolesFilter/state.ts
Labels: refactor

#218 ✨ 글로벌 네비게이션 바 적용
  apps/client/src/components/modal/ReSignInModal.tsx
  apps/client/src/components/nav/GlobarNavigationBar.tsx
  apps/client/src/components/ui/button.tsx
  apps/client/src/components/ui/layout.tsx
  apps/client/src/feature/landing/ui/PostCard.tsx
  apps/client/src/pages/CreateCompanyPage.tsx
  apps/client/src/pages/CreatePostPage.tsx
  apps/client/src/pages/CreateResumePage.tsx
  apps/client/src/pages/EmailVerifyPage.tsx
  apps/client/src/pages/LandingPage.tsx
  apps/client/src/pages/LocalSignUpPage.tsx
  apps/client/src/pages/MyPage.tsx
  apps/client/src/pages/PostDetailPage.tsx
  apps/client/src/pages/ResumeDetailPage.tsx
  apps/client/src/pages/ResumeListPage.tsx
  apps/client/src/pages/SignInSelectPage.tsx
  apps/client/src/pages/SignUpCompletePage.tsx
  apps/client/src/pages/SignUpSelectPage.tsx
  apps/client/src/pages/VentureCapitalLandingPage.tsx
  apps/client/src/shared/route/useRouteNavigation.ts
  apps/client/tailwind.config.js
Labels: feature

#220 ✨ 직군 선택 시 전체 체크 기능 생성
  apps/client/package.json
  apps/client/public/svg/arrow_down.svg
  apps/client/src/components/ui/checkbox.tsx
  apps/client/src/entities/asset.ts
  apps/client/src/feature/landing/ui/FilterSection.tsx
  apps/client/src/feature/landing/ui/RolesFilter.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/shared/auth/AuthAdminSwitchRoute.tsx
  apps/client/src/util/format.ts
  packages/api/src/apis/localServer/apis.ts
  yarn.lock
Labels: feature

#224 💄 페이지 breakpoint 피그마와 동일하게 픽셀 조정
  apps/client/src/components/nav/GlobarNavigationBar.tsx
  apps/client/src/pages/LandingPage.tsx
  apps/client/tailwind.config.js
Labels: feature

#229 ✨ 모집 중 및 시리즈 필터 모달 생성
  apps/client/package.json
  apps/client/src/components/ui/button.tsx
  apps/client/src/components/ui/popover.tsx
  apps/client/src/components/ui/radio-group.tsx
  apps/client/src/entities/post.ts
  apps/client/src/feature/landing/hooks/useGetPosts.ts
  apps/client/src/feature/landing/ui/FilterSection.tsx
  apps/client/src/feature/post/service/postService.ts
  yarn.lock
Labels: feature

#232 ✨ 북마크 추가 및 삭제 기능 생성
  apps/client/package.json
  apps/client/public/svg/bookmark_selected.svg
  apps/client/public/svg/bookmark_unselected.svg
  apps/client/public/svg/person.svg
  apps/client/src/components/modal/SignInForBookmarkModal.tsx
  apps/client/src/components/ui/layout.tsx
  apps/client/src/components/ui/popover.tsx
  apps/client/src/components/ui/slider.tsx
  apps/client/src/entities/asset.ts
  apps/client/src/entities/post.ts
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/landing/ui/FilterSection.tsx
  apps/client/src/feature/landing/ui/PostCard.tsx
  apps/client/src/feature/post/service/postService.ts
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/feature/post/ui/PostDetailView.tsx
  apps/client/src/feature/resume/ui/ResumeList.tsx
  apps/client/src/feature/user/ui/MyInfo.tsx
  apps/client/src/feature/ventureCapital/ui/MyCompanyList.tsx
  apps/client/src/mocks/post/schemas.ts
  apps/client/src/pages/LandingPage.tsx
  apps/client/src/shared/modal/hooks.ts
  apps/client/src/shared/route/useRouteNavigation.ts
  apps/client/tailwind.config.js
  packages/api/src/apis/localServer/apis.ts
  packages/api/src/apis/localServer/schemas.ts
  yarn.lock
Labels: feature

#235 🐛 이미지가 존재하지 않는 경우 대응
  apps/client/src/feature/landing/ui/PostCard.tsx
Labels: bug

#237 ✨ 페이지네이션 바 생성
  apps/client/src/components/ui/pagination.tsx
  apps/client/src/feature/landing/index.tsx
  apps/client/src/feature/landing/ui/Pagination.tsx
  apps/client/src/feature/landing/ui/PaginationBar.tsx
  apps/client/src/mocks/post/data.ts
  apps/client/src/mocks/post/schemas.ts
  apps/client/src/pages/LandingPage.tsx
Labels: feature

#239 ✨ 랜딩페이지 스켈레톤 로딩 추가
  apps/client/src/components/ui/skeleton.tsx
  apps/client/src/feature/landing/hooks/useGetPosts.ts
  apps/client/src/feature/landing/index.tsx
  apps/client/src/feature/landing/ui/SkeletonPostCard.tsx
  apps/client/src/pages/LandingPage.tsx
Labels: feature

#241 👽️ 회사 및 공고 생성 관련 DTO 변경 사항 반영
  apps/client/src/App.tsx
  apps/client/src/components/modal/ReSignInModal.tsx
  apps/client/src/entities/post.ts
  apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  apps/client/src/feature/auth/ui/signUp/LocalSignUpForm.tsx
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/company/ui/PatchCompanyForm.tsx
  apps/client/src/feature/post/index.tsx
  apps/client/src/feature/post/service/postService.ts
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/feature/post/ui/PatchPostForm.tsx
  apps/client/src/feature/post/ui/PostDetailView.tsx
  apps/client/src/feature/ventureCapital/ui/MyCompanyList.tsx
  apps/client/src/pages/CreateCompanyPage.tsx
  apps/client/src/pages/CreatePostPage.tsx
  apps/client/src/shared/auth/CompanyProtectedRoute.tsx
  apps/client/src/shared/file/fileService.ts
  apps/client/src/shared/route/useRouteNavigation.ts
  apps/client/src/util/format.ts
  packages/api/src/apis/localServer/apis.ts
  packages/api/src/apis/localServer/schemas.ts
Labels: feature

#244 💄카드 컴포넌트 패딩 및 뱃지 위치 조정
  apps/client/src/components/nav/GlobarNavigationBar.tsx
  apps/client/src/components/ui/badge.tsx
  apps/client/src/feature/landing/ui/PostCard.tsx
  apps/client/src/pages/LandingPage.tsx
Labels: feature

#245 ✨ 회사 생성 시 마크다운 에디터 추가
  apps/client/src/App.tsx
  apps/client/src/feature/company/presentation/companypresentation.ts
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/tailwind.config.js
Labels: feature

#247 ✨ 남은 글자수 확인 기능 추가
  apps/client/src/App.tsx
  apps/client/src/feature/company/presentation/companypresentation.ts
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/presentation/postPresentation.ts
  apps/client/src/feature/post/ui/CreatePostForm.tsx
Labels: feature

#250 ✨ 공고 재작성 모달 추가
  apps/client/src/components/modal/CancelCheckModal.tsx
  apps/client/src/components/modal/RewritePostModal.tsx
  apps/client/src/components/ui/button.tsx
  apps/client/src/entities/route.ts
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/feature/resume/presentation/resumePresentation.ts
  apps/client/src/feature/resume/ui/CreateResumeForm.tsx
  apps/client/src/pages/CreateCompanyPage.tsx
  apps/client/src/pages/CreatePostPage.tsx
  apps/client/src/shared/auth/CompanyProtectedRoute.tsx
  apps/client/src/shared/route/useRouteNavigation.ts
Labels: feature

#253 💄 회사 공고 작성 페이지에서 기본 string input 스타일링 적용
  apps/client/src/components/form/FormContainer.tsx
  apps/client/src/components/input/LabelContainer.tsx
  apps/client/src/components/response/formResponse.tsx
  apps/client/src/components/ui/button.tsx
  apps/client/src/feature/auth/ui/signIn/GoogleSocialSignInButton.tsx
  apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
  apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  apps/client/src/feature/auth/ui/signUp/GoogleSocialSignUpButton.tsx
  apps/client/src/feature/auth/ui/signUp/LocalSignUpForm.tsx
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/pages/CreateCompanyPage.tsx
Labels: feature

#256 ♻️ 회사 생성 페이지 필드 컴포넌트 분리
  apps/client/src/components/field/ImageField.tsx
  apps/client/src/components/field/MarkdownEditorField.tsx
  apps/client/src/components/field/PdfField.tsx
  apps/client/src/components/field/StringField.tsx
  apps/client/src/components/field/StringSelectForm.tsx
  apps/client/src/components/field/StringWithLetterCountField.tsx
  apps/client/src/feature/company/presentation/companyPresentation.ts
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/company/ui/fields/ExternalLinkField.tsx
  apps/client/src/feature/company/ui/fields/HashtagField.tsx
  apps/client/src/feature/company/ui/fields/InvestAmountField.tsx
  apps/client/src/feature/company/ui/fields/InvestCompanyField.tsx
Labels: refactor

#258 companyPresentation 계층에서 input과 form에 사용하는 상태 함께 관리
  apps/client/src/components/field/ImageField.tsx
  apps/client/src/components/field/MarkdownEditorField.tsx
  apps/client/src/components/field/PdfField.tsx
  apps/client/src/components/field/StringField.tsx
  apps/client/src/components/field/StringSelectForm.tsx
  apps/client/src/components/field/StringWithLetterCountField.tsx
  apps/client/src/entities/input.ts
  apps/client/src/entities/post.ts
  apps/client/src/feature/company/presentation/companyFormPresentation.ts
  apps/client/src/feature/company/presentation/companyInputPresentation.ts
  apps/client/src/feature/company/presentation/companyPresentation.ts
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/company/ui/fields/ExternalLinkField.tsx
  apps/client/src/feature/company/ui/fields/HashtagField.tsx
  apps/client/src/feature/company/ui/fields/InvestAmountField.tsx
  apps/client/src/feature/company/ui/fields/InvestCompanyField.tsx
Labels: feature

#260 ♻️ 공고 생성 페이지에 공통 필드 컴포넌트 적용
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/pages/CreatePostPage.tsx
Labels: refactor

#262 ✨ 공고 생성 시 input 및 form state로 관리
  apps/client/src/components/form/FormContainer.tsx
  apps/client/src/feature/auth/ui/signIn/LocalLoginForm.tsx
  apps/client/src/feature/auth/ui/signUp/EmailVerifyForm.tsx
  apps/client/src/feature/auth/ui/signUp/LocalSignUpForm.tsx
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/presentation/postFormPresentation.ts
  apps/client/src/feature/post/presentation/postInputPresentation.ts
  apps/client/src/feature/post/presentation/postPresentation.ts
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/feature/resume/ui/CreateResumeForm.tsx
  packages/eslint-react/package.json
  yarn.lock
Labels: refactor

#263 💄 달력 인풋 스타일링
  apps/client/eslint.config.js
  apps/client/package.json
  apps/client/src/components/ui/calendar.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  yarn.lock
Labels: feature

#265 👽️ 회사 생성 API 변경사항 반영
  apps/client/src/entities/post.ts
  apps/client/src/feature/company/presentation/companyFormPresentation.ts
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/service/postService.ts
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/feature/post/ui/PostDetailView.tsx
  apps/client/src/shared/auth/AuthAdminSwitchRoute.tsx
  packages/api/src/apis/localServer/apis.ts
  packages/api/src/apis/localServer/schemas.ts
Labels: feature

#267 👽️ 공고 생성 API 변경사항 반영
  apps/client/src/entities/post.ts
  apps/client/src/feature/post/presentation/postFormPresentation.ts
  apps/client/src/feature/post/presentation/postInputPresentation.ts
  apps/client/src/feature/post/service/postService.ts
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  packages/api/src/apis/localServer/apis.ts
  packages/api/src/apis/localServer/schemas.ts
Labels: feature

#270 💄 슬로건 input 줄이 늘어날 때마다 textarea height가 증가하도록 설정
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/company/ui/fields/SloganField.tsx
  apps/client/src/feature/post/ui/CreatePostForm.tsx
  apps/client/src/feature/post/ui/field/JobCategoryField.tsx
Labels: feature

#272 💄 이미지 업로드 input 스타일링
  apps/client/public/svg/close_white.svg
  apps/client/public/svg/photo_camera.svg
  apps/client/src/components/field/ImageField.tsx
  apps/client/src/entities/asset.ts
  apps/client/src/feature/auth/ui/signUp/LocalSignUpForm.tsx
Labels: feature

#274 💄 투자 단계 및 투자사 정보 스타일링
  apps/client/package.json
  apps/client/src/components/button/CancelButton.tsx
  apps/client/src/components/field/ImageField.tsx
  apps/client/src/components/field/StringSelectField.tsx
  apps/client/src/components/field/StringSelectForm.tsx
  apps/client/src/components/ui/select.tsx
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/company/ui/fields/InvestCompanyField.tsx
  apps/client/src/feature/landing/ui/PostCard.tsx
  apps/client/src/util/postFormatFunctions.ts
  yarn.lock
Labels: feature

#276 💄 해시태그 input 스타일링
  apps/client/src/components/button/CancelButton.tsx
  apps/client/src/components/field/ImageField.tsx
  apps/client/src/feature/company/presentation/companyInputPresentation.ts
  apps/client/src/feature/company/ui/fields/HashtagField.tsx
Labels: feature

#278 💄 PDF 업로드 버튼 스타일링
  apps/client/public/svg/drive_folder_upload.svg
  apps/client/src/components/field/ImageField.tsx
  apps/client/src/components/field/PdfField.tsx
  apps/client/src/entities/asset.ts
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/company/ui/fields/HashtagField.tsx
  apps/client/src/feature/company/ui/fields/SloganField.tsx
  apps/client/src/feature/post/ui/PostDetailView.tsx
Labels: feature

#280 💄 외부 소개 링크 스타일링
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/company/ui/fields/ExternalLinkField.tsx
  apps/client/src/feature/post/ui/PostDetailView.tsx
Labels: feature

#282 🚑 이미지 링크가 요청에 반영되지 않는 오류 해결
  apps/client/src/components/field/ImageField.tsx
  apps/client/src/components/field/PdfField.tsx
  apps/client/src/feature/company/presentation/companyFormPresentation.ts
  apps/client/src/feature/company/presentation/companyInputPresentation.ts
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
Labels: feature

#285 🐛 공고 불러올 때 토큰 들어가지 않는 문제 해결 및 landingpageLink에 빈 문자열이 들어오면 undefined로 요청 보내기
  apps/client/src/feature/company/presentation/companyFormPresentation.ts
  apps/client/src/feature/company/ui/CreateCompanyForm.tsx
  apps/client/src/feature/post/service/postService.ts
  apps/client/src/feature/post/ui/PostDetailView.tsx
  apps/client/src/pages/LandingPage.tsx
  packages/api/src/apis/localServer/apis.ts
Labels: bug
